# Simple workflow for deploying static content to GitHub Pages
name: Deploy DocC

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: macos-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Switch Xcode 🔄
        run: sudo xcode-select --switch /Applications/Xcode_16.2.app

      - name: Build DocC
        run: |
          set -euo pipefail
          
          projectName="DocProj"
          repoName="DocProj"
          
          # List schemes and parse the output to get only the scheme names
          schemes=$(
            xcodebuild -list -project "$projectName.xcodeproj" | \
              awk '/Schemes:/{flag=1; next} /$/ {if(flag && $0 !~ /^(\s)*$/){print $1}else if(flag){exit}}'
          )
          
          for scheme in $schemes; do
            echo "Building DocC documentation for scheme: $scheme"
          
            xcodebuild clean docbuild -project "$projectName.xcodeproj" \
              -scheme "$scheme" \
              -derivedDataPath "/tmp/docbuild-$scheme" \
              -destination 'generic/platform=iOS Simulator' \
              -skipPackagePluginValidation \
              -allowProvisioningUpdates
          
            doccarchive_path=$(find "/tmp/docbuild-$scheme" -name "*.doccarchive" | head -n 1)
          
            echo "Found doccarchive at $doccarchive_path"
          
            xcrun docc process-archive transform-for-static-hosting \
              "$doccarchive_path" \
              --hosting-base-path "$repoName/$scheme" \
              --output-path "doccDocs/$scheme"
          
            # (Optional) Write redirect page inside the correct artifact folder
            echo "<script>window.location.href += \"/documentation/$scheme\"</script>" > "$scheme/index.html"
          done
          
      - name: Prep pages
        uses: actions/configure-pages@v5
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload docs directory
          path: 'doccDocs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

